[deps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[sources]
Clapeyron = {url = "https://github.com/ClapeyronThermo/Clapeyron.jl"}